### ISSUE TITLE
你好，这个程序运行起来很漂亮，有一个问题想请教一下

### ISSUE THREAD

**Issue by jkddw** [shenshikexmu/ImuCalibration-Poistion#1]
data.mat里的数据是怎么定义的，加速度，陀螺仪，磁力计的单位是什么，我是不是可以导入其他型号的imu的数据

**Comment by shenshikexmu** [comment]
只用到加速度、陀螺仪，单位都是国际标准单位m/s 、rad/s

**Comment by CaiXunKunJiNiTaiMei** [comment]
你好，我想请问一下data.mat中的每一列数据的定义是什么，我这里只看数值的话无法分辨，谢谢

**Comment by shenshikexmu** [comment]
data :time accelerometer   gyroscope   magnetometer

**Comment by jkddw** [comment]
你好，最近我在用自己采集的imu数据输入Mahony算法进行姿态的计算，结果上无论多少采样频率，输出的Quaternion都有很大的延迟，比如0.1s的姿态改变，姿态会有一个平滑变化的过程，会在3s后输出与实际相符的姿态，具体matlab程序出自https://github.com/xioTechnologies/Oscillatory-Motion-Tracking-With-x-IMU，关于算法的参数我也不是很理解，不知道博主对此有没有什么头绪，方便的话可以有联系方式向你请教吗

**Comment by shenshikexmu** [comment]
是实时跑吗？也许是你电脑串口的问题？也许是你的时间间隔和源代码的时间间隔设置不一样的问题？其他出现问题的原因我想不到了，大概看了一下他的代码，发出来的，应该不是源代码的问题。（我自己不太习惯看别人的代码，一般都是自己看论文或推公式直接写代码，这样比较容易找bug，用别人的代码，找bug是挺让人沮丧的事，类似于追女生，总是猜，又猜不对）

**Comment by jkddw** [comment]
谢谢解答，还有个问题你程序里的data.mat和我的数据不一样，比如这一行，我的数据依次是gyroscope accelerometer  magnetometer 0.63,-0.35,0.14,0.628208,0.060032,0.613312,0.21054,0.28362,-0.6205999999999999
单位和你回复的是一样的，m/s 、rad/s可是data.mat里的数据似乎不是用这种单位的，比如data.mat的一行
0.0100000000000000	-757 	-1779	432	 -2	 -1	0	295	 -105	1

**Comment by shenshikexmu** [comment]
我的数据是IMU传到串口的数据，这个数据乘以校正后的参数就是以m/s 、rad/s为单位的数据

**Comment by jkddw** [comment]
校正这一步具体是在哪里做的，如果我想把校正后的数据输入该程序该怎么做

**Comment by shenshikexmu** [comment]
Ta,Ka,Ba,Tg,Kg,Bg,Tm2a,Bm这些就是校正的参数，在哪里算自己找一下吧。

**Comment by jkddw** [comment]
好的，我仔细看看，非常感谢
